# Jekyll Configuration

title: "Phobos"
description: "Work in progress"
author: "Bahadir Coskun"
baseurl: ""
url: "https://badiba.github.io/phobos-site/"
theme: jekyll-theme-modernist

# Minima theme settings
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
